version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '07:00'
    open-pull-requests-limit: 7
    rebase-strategy: 'disabled'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '06:00'
    open-pull-requests-limit: 5
    rebase-strategy: 'disabled'